name: Build and publish
on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - develop

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      go_version: ${{ steps.go-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract Go version from go.mod
        id: go-version
        run: |
          GO_VERSION=$(make print-go-version)
          echo "Extracted Go version: $GO_VERSION"
          echo "version=$GO_VERSION" >> "$GITHUB_OUTPUT"

  build_go_binary_and_release:
    needs: setup
    name: Build go binary and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        # As this repo is a public fork the public setup-go action is used here instead of our private one
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.setup.outputs.go_version }}

      - name: Build binary
        run: |
          env GOOS=linux GOARCH=amd64 go build -o dist/linux-x64
          env GOOS=linux GOARCH=arm64 go build -o dist/linux-arm64
          env GOOS=darwin GOARCH=amd64 go build -o dist/macos-x64
          env GOOS=darwin GOARCH=arm64 go build -o dist/macos-arm64
          env GOOS=windows GOARCH=amd64 go build -o dist/windows-x64

      - name: Determine next version
        id: next-version
        run: |
          LAST_TAG=$(git tag --list "v*" --sort=-v:refname | head --lines=1)

          if [[ -z "$LAST_TAG" ]]; then
            NEXT_VERSION="v1"
          else
            VERSION_NUM=${LAST_TAG#v}
            NEXT_VERSION="v$((VERSION_NUM + 1))"
          fi

          echo "next-version=$NEXT_VERSION" >> "$GITHUB_OUTPUT"

      - name: Create tag
        run: |
          git config --global user.email "${{ github.event.pusher.email }}"
          git config --global user.name "${{ github.event.pusher.name }}"
          git add .
          git commit --message 'release: ${{ steps.next-version.outputs.next-version }}'
          git tag ${{ steps.next-version.outputs.next-version }}
          git push origin --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next-version.outputs.next-version }}
          release_name: ${{ steps.next-version.outputs.next-version }}
          body: ""
          draft: false
          prerelease: false

