name: Test
on:
  push:
    tags-ignore:
      - "*.*"
    branches:
      - "**"

jobs:
  test_on_machine:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15.5

      - name: Build binary
        run: go build -o dist/$(echo "${{ runner.os }}" | tr "[:upper:]" "[:lower:]")-${{ runner.arch }}
        shell: bash

      - name: Create temp files
        shell: bash
        run: |
          mkdir -p temp/{dir1,dir2,dir3}/{subdir1,subdir2,subdir3}
          echo "fileexample" > temp/file.txt
          cat temp/file.txt | tee temp/dir1/file.txt temp/dir2/file.txt temp/dir3/file.txt temp/dir1/subdir1/file.txt temp/dir2/subdir2/file.txt temp/dir3/subdir3/file.txt

      - name: Put cache
        uses: ./
        with:
          action: put
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CACHING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CACHING }}
          bucket: ${{ vars.AWS_BUCKET_NAME_CACHING }}
          key: ${{ hashFiles('action.yml') }}-${{ matrix.os }}
          artifacts: |
            temp/*

      - name: Remove temp folder
        shell: bash
        run: rm -rf temp

      - name: Get cache
        uses: ./
        with:
          action: get
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CACHING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CACHING }}
          bucket: ${{ vars.AWS_BUCKET_NAME_CACHING }}
          key: ${{ hashFiles('action.yml') }}-${{ matrix.os }}

      - name: List cache folder
        shell: bash
        run: ls temp

      - name: Delete cache
        uses: ./
        with:
          action: delete
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_CACHING }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_CACHING }}
          bucket: ${{ vars.AWS_BUCKET_NAME_CACHING }}
          key: ${{ hashFiles('action.yml') }}-${{ matrix.os }}
